FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*
COPY index.html  /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]  #This command starts the nginx server in the foreground, which is necessary for the container to keep running.




