FROM node:18 AS builder
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .



FROM node:18-alpine
WORKDIR /app
RUN adduser -D appuser         
COPY --from=builder /app /app   
RUN chown -R appuser:appuser /app    
USER appuser
CMD ["node", "server.js"]